---
name: "TvHeadend Client"
guid: "d2762daa-c6a2-4ede-b513-36b09a9f1752"
imageUrl: "https://raw.githubusercontent.com/baywolf-studios/jellyfin-plugin-tvheadend-client/main/images/jellyfin-plugin-tvheadend-client.png"
version: "8.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "A plugin that brings TvHeadend's Live TV and DVR capabilities into Jellyfin."
description: >
  This plugin securely connects Jellyfin with your TvHeadend setup. Stream live TV, navigate the full EPG, and control DVR scheduling. It exclusively uses Digest Authentication for secure access and proxies Tvheadend's image cache.

category: "Live TV"
owner: "Bay Wolf Studios LLC"
artifacts:
  - "Jellyfin.Plugin.TvHeadendClient.dll"
changelog: |-
  - feat: Added ability to allow fMP4 transcoding container (#29) @matthewpritchett
