---
name: "TvHeadend Client"
guid: "d2762daa-c6a2-4ede-b513-36b09a9f1752"
version: untagged-9879fd015336b24dfd1c
targetAbi: "10.11.0.0"
framework: "net8.0"
overview: "A plugin that brings TvHeadend's Live TV and DVR capabilities into Jellyfin."
description: >
  This plugin securely connects Jellyfin with your TvHeadend setup. Stream live TV, navigate the full EPG, and control DVR scheduling. It exclusively uses Digest Authentication for secure access and proxies Tvheadend's image cache.

category: "Live TV"
owner: "Bay Wolf Studios LLC"
artifacts:
  - "Jellyfin.Plugin.TvHeadendClient.dll"
changelog: |-
  - Formatting (#1) @matthewpritchett
